[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["openzeppelin=lib/openzeppelin-contracts/"]
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
    { access = "read", path = "./images" },
]

[lint]
exclude_lints = [
  "mixed-case-variable",
  "mixed-case-function",
  "erc20-unchecked-transfer"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
